name: JSON Image Linker
options:
  bundleIdPrefix: com.harshu
targets:
  JSON Image Linker:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: JSON Image Linker
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.harshu.JSON-Image-Linker
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_IDENTITY: "-"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: JSON Image Linker/JSON_Image_Linker.entitlements
